title: marketing • events • design
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2867384
  brandStrength: 0.6875
  lightness: 0.5949821
  brandColors:
    - '#DFD9CF'
    - '#141417'
    - '#90201E'
    - '#556C91'
    - '#992988'
  rhythmicContrast: 0.5985663
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: andreamikla
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3924731
layout_spectrum: 0.55622
