title: marketing • events • design
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3046595
  brandStrength: 0.5
  lightness: 0.5197133
  brandColors:
    - '#FFFFFF'
    - '#5E5E5E'
    - '#AFAFAF'
    - '#0E151F'
    - '#F1EB4B'
  rhythmicContrast: 0.7204301
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: andreamikla
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3405018
layout_spectrum: 0.6415771
