name: andreamikla
favicon: null
layout_spectrum: 0.94737
typography_spectrum: 0.11409
title: marketing • events • design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdfe'
    - '#636466'
    - '#9d9d9f'
    - '#e1e0e1'
    - '#7c7c7e'
  brandStrength: 0.6875
  lightness: 0.9039010962005705
  saturation: 0.13330895826220512
  rhythmicContrast: 0.05720983003266156
purpose: []
