name: andreamikla
favicon: null
layout_spectrum: 0.5397412304300815
typography_spectrum: 0.7747292439453304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5951385232619941
  lightness: 0.9039010962005705
  saturation: 0.13330895826220512
  rhythmicContrast: 0.05720983003266156
purpose: []
