title: marketing • events • design
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6863799
  brandStrength: 0.01971326
  lightness: 0.8978494
  brandColors:
    - '#FFFFFF'
    - '#5E5E5E'
    - '#AFAFAF'
    - '#0E151F'
    - '#F1EB4B'
  rhythmicContrast: 0.5806451
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: andreamikla
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3405018
layout_spectrum: 0.7939068
